// Mocks generated by Mockito 5.0.15 from annotations
// in technical_test/test/auth_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;

import 'package:firebase_auth/firebase_auth.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:technical_test/model/auth_process.dart' as _i4;
import 'package:technical_test/model/result.dart' as _i2;
import 'package:technical_test/model/user.dart' as _i5;
import 'package:technical_test/services/auth_service.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeResult_0<T> extends _i1.Fake implements _i2.Result<T> {}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Result<_i4.AuthProcess> verifyPhone(_i5.User? user,
          {dynamic Function(_i6.PhoneAuthCredential)? onVerificationCompleted,
          dynamic Function(_i6.FirebaseAuthException)? onVerificationFailed,
          dynamic Function(String)? onCodeSent,
          dynamic Function(String)? onCodeAutoRetrievalTimeout}) =>
      (super.noSuchMethod(
              Invocation.method(#verifyPhone, [
                user
              ], {
                #onVerificationCompleted: onVerificationCompleted,
                #onVerificationFailed: onVerificationFailed,
                #onCodeSent: onCodeSent,
                #onCodeAutoRetrievalTimeout: onCodeAutoRetrievalTimeout
              }),
              returnValue: _FakeResult_0<_i4.AuthProcess>())
          as _i2.Result<_i4.AuthProcess>);
  @override
  _i7.Future<_i2.Result<_i5.User>> signInUser(_i5.User? user,
          {String? verificationId,
          _i6.PhoneAuthCredential? credential,
          String? smsCode}) =>
      (super.noSuchMethod(
              Invocation.method(#signInUser, [
                user
              ], {
                #verificationId: verificationId,
                #credential: credential,
                #smsCode: smsCode
              }),
              returnValue:
                  Future<_i2.Result<_i5.User>>.value(_FakeResult_0<_i5.User>()))
          as _i7.Future<_i2.Result<_i5.User>>);
  @override
  String toString() => super.toString();
}
